spring:
  application:
    name: stock-ticker-service

resilience4j:
  circuitbreaker:
    instances:
      circuit-breaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10

alphavantage:
  apikey: ${APIKEY}
  symbol: ${SYMBOL}
  ndays: ${NDAYS:3}
  url: "https://www.alphavantage.co/query"