openapi: 3.0.1
info:
  title: Stock Ticker
  description: Stock Ticker Application
  version: 1.0.0
servers:
  - url: /api
paths:
  /v1/stock/report:
    get:
      tags:
        - stock ticker
      summary: Get closing prices of a specific stock.
      operationId: getClosingQuote
      responses:
        503:
          description: Backend error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockDetails'

components:
  schemas:
    StockDetails:
      type: object
      properties:
        information:
          type: string
          example: 'Information from alphavantage'
        symbol:
          type: string
          example: 'MSFT'
        averageClosingPrice:
          type: double
          example: '22.00'
        averagePeriod:
          type: integer
          example: 5
        dailyClosingPrice:
          additionalProperties:
            type: double

    ErrorReport:
      type: object
      description: A specific error
      properties:
        message:
          type: string
          description: Human readable form of the error
      required:
        - code
        - message